### ISSUE TITLE
Clarification in the Licensing for the PS Windows Update module

### ISSUE THREAD

**Issue by glennsarti** [noma4i/puppet-windows_updates#10]
Hello, I noticed that this Puppet module re-vendors the PS Windows Update PowerShell module, presumably from https://www.powershellgallery.com/packages/PSWindowsUpdate/2.1.1.2

However, as this PowerShell module is closed source and does not explicitly state what license is used, I'd like to get clarification that you do have permission from the author (Michal Gajda) to redistribute that module.

Additionally, what license is this Puppet module distributed under as there does not appear to be a LICENSE file in this repo (but the metadata says Apache 2.0)

**Comment by noma4i** [comment]
I have added LICENSE file to this repo. Can't see any license attached powershellgallery so I have contacted with author.

![image](https://user-images.githubusercontent.com/210667/65847140-a762c600-e383-11e9-88c2-44872cb1adfb.png)

**Comment by noma4i** [comment]
Will update Readme once author responds

**Comment by noma4i** [comment]
Haven't heard anything back from Gajda. Will close this issue for now
