### ISSUE TITLE
A way to require a KB and/or install via KBs within a WinRM session?

### ISSUE THREAD

**Issue by petemounce** [noma4i/puppet-windows_updates#5]
I want to install the `vcredist2015` chocolatey package - within a WinRM session - which (transitively) depends on some KBs. Because of WinRM, chocolatey's way of doing this results in an access denied error 5 (https://support.microsoft.com/en-gb/help/2773898/windows-update-standalone-installer-wusa-returns-0x5-error-access-deni).

I'm now trying to use this module to install these KBs separately, first. Is there a way I can `require` that these KBs are installed, to make the `vcredist2015` chocolatey install depend on these having already been installed?

I'm not sure that that will work, though, since I'm still within WinRM - but I do see that the PSWindowsUpdate module that this wraps has support for creating a task-scheduler-based workaround for this (which is how the ansible implementation of this works around the WinRM security model I think)...?

**Comment by noma4i** [comment]
You can use chaining to ensure that KB installer run before. https://docs.puppet.com/puppet/5.0/lang_relationships.html#operands

**Comment by petemounce** [comment]
I'm working on a patch to use `Invoke-WUInstall.ps1` - how does the `checksums.json` file get generated, please?
